added drawing (not complete)
marl0vv/PROMETHEEMethodsApp pull request #11
Opened 2023-01-03 08:36 UTC by Awernett

2023-01-03 09:15 UTC, marl0vv requested changes
Нужны изменения к именам переменных и комментарии к рисованию прямых. Подробнее в комментариях постарался расписать.

2023-01-03 09:15 UTC, marl0vv commented on drawing.cpp
>      QGraphicsTextItem* item01 = new QGraphicsTextItem();
Имя item01 не отражает, чем является эта переменная. Так как эти переменные обозначает 0.0 у левого и правого прямоугольника, то могу предложить имя zeroLabelLeft и zeroLabelRight

Возможно, есть варианты получше, но item01 отпугивает и не совсем понятно, что это значит. Мб @MetalPizzaCat может что-нибудь предложить

2023-01-03 09:15 UTC, marl0vv commented on drawing.cpp
>      QGraphicsTextItem* PhiPlus = new QGraphicsTextItem();
Возможно, phiPlusLabel и phiMinusLabel будут более подходящими именами.

2023-01-03 09:15 UTC, marl0vv commented on drawing.cpp
> +    double php[drawingAlternativesAmount];
Если придерживаться раннее введённых обозначений, то phiPositive и phiNegative будут иметь больше смысла

2023-01-03 09:15 UTC, marl0vv commented on drawing.cpp
> +        phn[i]=1-drawingAlternatives[i].getPhiNegative();
Так. С этого момента мне нужно много комментариев, чтобы я правильно понял, что происходит.
Тут мы добавляем в массивы phi из массива, который мы получили из MainWindow
С Positive понятно.
С Negative не совсем понимаю, но догадываюсь, что мы отнимаем от единицы, чтобы получить отрицательную координату.

2023-01-03 09:15 UTC, marl0vv commented on drawing.cpp
> +    }
Тут происходит координатная магия. Я примерно догадываюсь, но не совсем понимаю. Так как нам нужно это описывать в текстовой записке, запрашиваю комментарии с пояснениями.

2023-01-03 09:48 UTC, MetalPizzaCat requested changes

2023-01-03 09:48 UTC, MetalPizzaCat commented on drawing.cpp
>      QGraphicsTextItem* item01 = new QGraphicsTextItem();
`graphLabelZeroRight` может быть? Но `zeroLabelRight` тоже терпимо

2023-01-03 09:48 UTC, MetalPizzaCat commented on drawing.cpp
> +    double php[drawingAlternativesAmount];
С научной точки зрения верная заметка, с точки зрения дизайна GUI приложения `phiMinus`/`phiPlus` имееют смысл ибо они буквально элемент описывают

2023-01-03 09:48 UTC, MetalPizzaCat commented on drawing.h
> +    explicit Drawing(QWidget *parent,std::vector<Actions> a,int n);
переменным стоит давать осмысленные имена `a` и `n` не понятны
`actions` и `count` будут иметь больше смысла

И передавать сложные конструкции (структуры, классы, vector, array, map и тд) стоит через ссылку
то есть `std::vector<Actions> &actions`. Если значения в аргументе менятся не будут то лучше по константой сылке `std::vector<Actions> const &actions`. Ибо в ином случае происходит копирование значений памяти, что не очень эффективно

2023-01-03 09:48 UTC, MetalPizzaCat commented on drawing.cpp
>      QPen blackpen(Qt::black);
и не стоит сокращать слова, сложнее будет понять суть программы в последущих чтениях

2023-01-03 09:51 UTC, MetalPizzaCat commented on drawing.cpp
> +    double php[drawingAlternativesAmount];
имена `php` и `phn` не имеют смысла, им стоит дать более осмысленные имена иначе код сложно понять

2023-01-03 09:52 UTC, MetalPizzaCat requested changes
Мало читабельный код

2023-01-03 09:52 UTC, MetalPizzaCat commented on drawing.cpp
> +    double php[drawingAlternativesAmount];
имена php и phn не имеют смысла, им стоит дать более осмысленные имена иначе код сложно понять

2023-01-03 10:00 UTC, Awernett commented on drawing.cpp
>      QGraphicsTextItem* PhiPlus = new QGraphicsTextItem();
сделано

2023-01-03 10:00 UTC, Awernett commented on drawing.cpp
> +    double php[drawingAlternativesAmount];
сделано

2023-01-03 10:01 UTC, Awernett commented on drawing.h
> +    std::vector<Actions> drawingAlternatives; //все альтернативы
сделано

2023-01-03 10:04 UTC, Awernett commented on drawing.cpp
>      QPen blackpen(Qt::black);
сделано

2023-01-03 10:05 UTC, Awernett commented on drawing.cpp
>      QGraphicsTextItem* item01 = new QGraphicsTextItem();
сделано

2023-01-05 01:21 UTC, MetalPizzaCat approved these changes

2023-01-06 00:46 UTC, merged